version: "3.9"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3200/loki/api/v1/push"
      loki-external-labels: "type=dev,job=docker,container_name={{.Name}}"

services:
  frontend:
    <<: *logging
    image: ${REGISTRY_HOST}/${GIT_REPO_NAME}.${BRANCH_NAME}
    labels:
      - "traefik.enable=true"
      - "custom.label=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "io.portainer.accesscontrol.teams=devs,managers"
    networks:
      - default

  traefik:
    <<: *logging
    image: traefik:2.7
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.constraints=Label(`custom.label`,`${COMPOSE_PROJECT_NAME}`)"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${COMPOSE_PROJECT_NAME}"
      - "--entrypoints.web.address=:80"
    labels:
      - "io.portainer.accesscontrol.teams=devs,managers"
    ports:
      - "${WEB_PORT:-80}"
      - "127.0.0.1::8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    labels:
      - "io.portainer.accesscontrol.teams=devs,managers"
